create table if not exists addresses
(
  id        bigint generated by default as identity
    primary key,
  apartment varchar(255),
  area      varchar(255),
  city      varchar(255),
  house     varchar(255),
  region    varchar(255),
  street    varchar(255)
);

create table if not exists categories
(
  id         bigint generated by default as identity
    primary key,
  created_at timestamp(6),
  image_url  varchar(255),
  name       varchar(255) not null,
  updated_at timestamp(6)
);

create table if not exists products
(
  id          bigint generated by default as identity
    primary key,
  created_at  timestamp(6),
  description varchar(255),
  image_url   varchar(255),
  name        varchar(255)     not null,
  price       double precision not null,
  stock       integer          not null,
  updated_at  timestamp(6),
  category_id bigint
    constraint fkog2rp4qthbtt2lfyhfo32lsw9
      references categories
);

create table if not exists users
(
  id         bigint generated by default as identity
    primary key,
  created_at timestamp(6),
  email      varchar(255),
  first_name varchar(255),
  last_name  varchar(255),
  password   varchar(255) not null,
  phone      varchar(255),
  role       varchar(255)
    constraint users_role_check
      check ((role)::text = ANY
             ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
  updated_at timestamp(6),
  address_id bigint
    constraint ukhbvhqvjgmhd5omxyo67ynvbyp
      unique
    constraint fke8vydtk7hf0y16bfm558sywbb
      references addresses
);

create table if not exists carts
(
  id          bigint generated by default as identity
    primary key,
  total_price double precision,
  user_id     bigint
    constraint uk64t7ox312pqal3p7fg9o503c2
      unique
    constraint fkb5o626f86h46m4s7ms6ginnop
      references users
);


create table if not exists cart_items
(
  id         bigint generated by default as identity
    primary key,
  quantity   integer,
  cart_id    bigint
    constraint fkpcttvuq4mxppo8sxggjtn5i2c
      references carts,
  product_id bigint
    constraint fk1re40cjegsfvw58xrkdp6bac6
      references products
);


create table if not exists orders
(
  id           bigint generated by default as identity
    primary key,
  order_date   timestamp(6) not null,
  order_number varchar(10)
    constraint uknthkiu7pgmnqnu86i2jyoe2v7
      unique,
  status       varchar(255)
    constraint orders_status_check
      check ((status)::text = ANY
             ((ARRAY ['NEW'::character varying, 'PROCESSING'::character varying, 'PAID'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])),
  total_price  double precision,
  user_id      bigint       not null
    constraint fk32ql8ubntj5uh44ph9659tiih
      references users
);


create table if not exists delivery_addresses
(
  id        bigint generated by default as identity
    primary key,
  apartment varchar(255),
  area      varchar(255),
  city      varchar(255),
  house     varchar(255),
  region    varchar(255),
  street    varchar(255),
  order_id  bigint not null
    constraint uk93d8inf9aat9taywih3fsvo76
      unique
    constraint fka7hq9i1ex68litk9wdfgsp84j
      references orders
);


create table if not exists order_items
(
  id         bigint generated by default as identity
    primary key,
  price      double precision,
  quantity   integer,
  order_id   bigint not null
    constraint fkbioxgbv59vetrxe0ejfubep1w
      references orders,
  product_id bigint not null
    constraint fkocimc7dtr037rh4ls4l95nlfi
      references products
);
